# Check disk usage of gs://pangeo-data and upload CSV summary

name: Check disk usage of gs://pangeo-data

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  du-pangeo-data:
    name: Check
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-data/pangeo-datastore-flask'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gcsfs

      - name: Check disk usage
        run: |
          python scripts/du-pangeo-data.py
